### ISSUE TITLE
Error 0x80010135: Path too long

### ISSUE THREAD

**Issue by Nagle** [imagemin/imagemin-app#18]
![image001](https://cloud.githubusercontent.com/assets/236462/13989617/98c8b0a6-f0e7-11e5-8613-c8e0a7e92381.png)

Clicking on `SKIP` worked.

@octocat: Would be interesting if issues could be **blamed**.

**Comment by sindresorhus** [comment]
That's a problem with Explorer.exe not supporting long paths, and nothing specifically to do with this module. Use a better file browser or a better OS.
